bcsp.exe depth p_1.txt sol_1_d.txt
bcsp.exe hill p_1.txt sol_h1_t1.txt
bcsp.exe hill p_1.txt sol_h1_t2.txt
bcsp.exe hill p_1.txt sol_h1_t3.txt
bcsp.exe hill p_1.txt sol_h1_t4.txt
bcsp.exe hill p_1.txt sol_h1_t5.txt
bcsp.exe depth p_2.txt sol_2_d.txt
bcsp.exe hill p_2.txt sol_h2_t1.txt
bcsp.exe hill p_2.txt sol_h2_t2.txt
bcsp.exe hill p_2.txt sol_h2_t3.txt
bcsp.exe hill p_2.txt sol_h2_t4.txt
bcsp.exe hill p_2.txt sol_h2_t5.txt
bcsp.exe depth p_3.txt sol_3_d.txt
bcsp.exe hill p_3.txt sol_h3_t1.txt
bcsp.exe hill p_3.txt sol_h3_t2.txt
bcsp.exe hill p_3.txt sol_h3_t3.txt
bcsp.exe hill p_3.txt sol_h3_t4.txt
bcsp.exe hill p_3.txt sol_h3_t5.txt
bcsp.exe depth p_4.txt sol_4_d.txt
bcsp.exe hill p_4.txt sol_h4_t1.txt
bcsp.exe hill p_4.txt sol_h4_t2.txt
bcsp.exe hill p_4.txt sol_h4_t3.txt
bcsp.exe hill p_4.txt sol_h4_t4.txt
bcsp.exe hill p_4.txt sol_h4_t5.txt
bcsp.exe depth p_5.txt sol_5_d.txt
bcsp.exe hill p_5.txt sol_h5_t1.txt
bcsp.exe hill p_5.txt sol_h5_t2.txt
bcsp.exe hill p_5.txt sol_h5_t3.txt
bcsp.exe hill p_5.txt sol_h5_t4.txt
bcsp.exe hill p_5.txt sol_h5_t5.txt
bcsp.exe depth p_6.txt sol_6_d.txt
bcsp.exe hill p_6.txt sol_h6_t1.txt
bcsp.exe hill p_6.txt sol_h6_t2.txt
bcsp.exe hill p_6.txt sol_h6_t3.txt
bcsp.exe hill p_6.txt sol_h6_t4.txt
bcsp.exe hill p_6.txt sol_h6_t5.txt
bcsp.exe depth p_7.txt sol_7_d.txt
bcsp.exe hill p_7.txt sol_h7_t1.txt
bcsp.exe hill p_7.txt sol_h7_t2.txt
bcsp.exe hill p_7.txt sol_h7_t3.txt
bcsp.exe hill p_7.txt sol_h7_t4.txt
bcsp.exe hill p_7.txt sol_h7_t5.txt
bcsp.exe depth p_8.txt sol_8_d.txt
bcsp.exe hill p_8.txt sol_h8_t1.txt
bcsp.exe hill p_8.txt sol_h8_t2.txt
bcsp.exe hill p_8.txt sol_h8_t3.txt
bcsp.exe hill p_8.txt sol_h8_t4.txt
bcsp.exe hill p_8.txt sol_h8_t5.txt
bcsp.exe depth p_9.txt sol_9_d.txt
bcsp.exe hill p_9.txt sol_h9_t1.txt
bcsp.exe hill p_9.txt sol_h9_t2.txt
bcsp.exe hill p_9.txt sol_h9_t3.txt
bcsp.exe hill p_9.txt sol_h9_t4.txt
bcsp.exe hill p_9.txt sol_h9_t5.txt
bcsp.exe depth p_10.txt sol_10_d.txt
bcsp.exe hill p_10.txt sol_h10_t1.txt
bcsp.exe hill p_10.txt sol_h10_t2.txt
bcsp.exe hill p_10.txt sol_h10_t3.txt
bcsp.exe hill p_10.txt sol_h10_t4.txt
bcsp.exe hill p_10.txt sol_h10_t5.txt
